[package]
name = "rw"
description = "Documentation engine - CLI"
repository = "https://github.com/yumike/rw"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rw"
path = "src/main.rs"

[lints]
workspace = true

[features]
default = []
embed-assets = ["rw-assets/embed"]

[dependencies]
rw-assets = { workspace = true }
rw-config = { workspace = true }
rw-confluence = { workspace = true }
rw-server = { workspace = true }
rw-site = { workspace = true }
rw-storage = { workspace = true }
rw-storage-fs = { workspace = true }
rw-techdocs = { workspace = true }

clap = { version = "4", features = ["derive", "env"] }
console = "0.16"
glob = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
