[package]
name = "docstage-core"
description = "High-performance markdown renderer for Docstage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
docstage-confluence-renderer = { workspace = true }
docstage-diagrams = { workspace = true }
docstage-renderer = { workspace = true }
pulldown-cmark = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
